# Generated by Django 2.1.1 on 2019-07-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20190725_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodstype',
            old_name='goodstype_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='goodstype',
            old_name='goodstype_img',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='goodstype',
            name='goodstype_description',
        ),
        migrations.AddField(
            model_name='goodstype',
            name='description',
            field=models.TextField(default=1, max_length=30, verbose_name='商品类型描述'),
            preserve_default=False,
        ),
    ]
