# Generated by Django 2.1.1 on 2019-07-29 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_auto_20190725_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30, verbose_name='id订单编号')),
                ('order_count', models.IntegerField(verbose_name='商品数量')),
                ('order_price', models.FloatField(verbose_name='商品总价')),
                ('order_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Address', verbose_name='订单地址')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Buyer', verbose_name='订单用户')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30, verbose_name='订单编号')),
                ('Goods_id', models.IntegerField(verbose_name='商品id')),
                ('Goods_name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('Goods_price', models.FloatField(verbose_name='商品价格')),
                ('Goods_number', models.IntegerField(verbose_name='商品数量')),
                ('Goods_total', models.FloatField(verbose_name='商品总价')),
                ('Goods_store', models.IntegerField(verbose_name='商店id')),
            ],
        ),
    ]
