# Generated by Django 2.1.1 on 2019-07-29 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0005_auto_20190729_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='Goods_id',
            new_name='goods_id',
        ),
    ]
